blank_issues_enabled: true
contact_links:
  - name:  é¡¹ç›®æ–‡æ¡£
    url: https://wiki.msaber.fun
    about: æŸ¥çœ‹å®Œæ•´çš„é¡¹ç›®æ–‡æ¡£å’Œä½¿ç”¨æŒ‡å—
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/xylplm/media-saber-ctmd/discussions
    about: ä¸€èˆ¬æ€§è®¨è®ºã€æƒ³æ³•åˆ†äº«å’Œç¤¾åŒºäº¤æµ
